//! Task submission: deduplication, priority upgrade, and requeue logic.

use sqlx::Row;

use crate::task::{SubmitOutcome, TaskSubmission, MAX_PAYLOAD_BYTES};

use super::{StoreError, TaskStore};

/// Core dedup logic for a single task submission within an existing connection.
///
/// Performs the three-step dedup: INSERT OR IGNORE → upgrade priority on
/// pending/paused → mark requeue on running. Shared by both `submit()` and
/// `submit_batch()` to eliminate duplication.
pub(crate) async fn submit_one(
    conn: &mut sqlx::pool::PoolConnection<sqlx::Sqlite>,
    sub: &TaskSubmission,
) -> Result<SubmitOutcome, StoreError> {
    let key = sub.effective_key();
    let priority = sub.priority.value() as i32;
    let fail_fast_val: i32 = if sub.fail_fast { 1 } else { 0 };

    let result = sqlx::query(
        "INSERT OR IGNORE INTO tasks (task_type, key, label, priority, payload, expected_read_bytes, expected_write_bytes, expected_net_rx_bytes, expected_net_tx_bytes, parent_id, fail_fast, group_key)
         VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
    )
    .bind(&sub.task_type)
    .bind(&key)
    .bind(&sub.label)
    .bind(priority)
    .bind(&sub.payload)
    .bind(sub.expected_read_bytes)
    .bind(sub.expected_write_bytes)
    .bind(sub.expected_net_rx_bytes)
    .bind(sub.expected_net_tx_bytes)
    .bind(sub.parent_id)
    .bind(fail_fast_val)
    .bind(&sub.group_key)
    .execute(&mut **conn)
    .await?;

    if result.rows_affected() > 0 {
        return Ok(SubmitOutcome::Inserted(result.last_insert_rowid()));
    }

    // Dedup hit — try to upgrade priority on pending/paused tasks.
    let row = sqlx::query(
        "UPDATE tasks SET priority = ?
         WHERE key = ? AND status IN ('pending', 'paused') AND priority > ?
         RETURNING id",
    )
    .bind(priority)
    .bind(&key)
    .bind(priority)
    .fetch_optional(&mut **conn)
    .await?;

    if let Some(r) = row {
        return Ok(SubmitOutcome::Upgraded(r.get("id")));
    }

    // Dedup hit on running/paused task — mark for re-queue.
    let row = sqlx::query(
        "UPDATE tasks SET requeue = 1, requeue_priority = ?
         WHERE key = ? AND status IN ('running', 'paused')
           AND (requeue = 0 OR requeue_priority > ?)
         RETURNING id",
    )
    .bind(priority)
    .bind(&key)
    .bind(priority)
    .fetch_optional(&mut **conn)
    .await?;

    match row {
        Some(r) => Ok(SubmitOutcome::Requeued(r.get("id"))),
        None => Ok(SubmitOutcome::Duplicate),
    }
}

impl TaskStore {
    /// Submit a new task.
    ///
    /// Returns [`SubmitOutcome::Inserted`] if the task was enqueued,
    /// [`SubmitOutcome::Upgraded`] if a duplicate existed but its priority
    /// was upgraded, or [`SubmitOutcome::Duplicate`] if a duplicate existed
    /// with equal or higher priority.
    ///
    /// When `sub.key` is `None`, the dedup key is auto-generated by hashing
    /// the task type and payload.
    pub async fn submit(&self, sub: &TaskSubmission) -> Result<SubmitOutcome, StoreError> {
        if let Some(ref p) = sub.payload {
            if p.len() > MAX_PAYLOAD_BYTES {
                return Err(StoreError::PayloadTooLarge);
            }
        }

        let mut conn = self.begin_write().await?;
        tracing::debug!(task_type = %sub.task_type, "store.submit: INSERT start");
        let outcome = submit_one(&mut conn, sub).await?;
        tracing::debug!(task_type = %sub.task_type, "store.submit: INSERT end");
        sqlx::query("COMMIT").execute(&mut *conn).await?;
        Ok(outcome)
    }

    /// Submit multiple tasks in a single transaction. Returns a `Vec` with one
    /// [`SubmitOutcome`] per input.
    ///
    /// This is significantly faster than calling [`submit`](Self::submit) in a
    /// loop because all inserts share a single SQLite transaction (one
    /// `BEGIN`/`COMMIT` pair instead of N implicit transactions).
    pub async fn submit_batch(
        &self,
        submissions: &[TaskSubmission],
    ) -> Result<Vec<SubmitOutcome>, StoreError> {
        // Pre-validate all payloads before starting the transaction
        // to avoid partial inserts on validation errors.
        for sub in submissions {
            if let Some(ref p) = sub.payload {
                if p.len() > MAX_PAYLOAD_BYTES {
                    return Err(StoreError::PayloadTooLarge);
                }
            }
        }

        let mut results = Vec::with_capacity(submissions.len());
        let mut conn = self.begin_write().await?;

        for sub in submissions {
            results.push(submit_one(&mut conn, sub).await?);
        }

        sqlx::query("COMMIT").execute(&mut *conn).await?;
        Ok(results)
    }
}

#[cfg(test)]
mod tests {
    use crate::priority::Priority;
    use crate::task::{SubmitOutcome, TaskMetrics, TaskSubmission, MAX_PAYLOAD_BYTES};

    use super::super::TaskStore;

    async fn test_store() -> TaskStore {
        TaskStore::open_memory().await.unwrap()
    }

    fn make_submission(key: &str, priority: Priority) -> TaskSubmission {
        TaskSubmission::new("test")
            .key(key)
            .priority(priority)
            .payload_raw(b"hello".to_vec())
            .expected_io(1000, 500)
    }

    #[tokio::test]
    async fn submit_and_pop() {
        use crate::task::TaskStatus;
        let store = test_store().await;
        let sub = make_submission("job-1", Priority::NORMAL);
        let expected_key = sub.effective_key();

        let outcome = store.submit(&sub).await.unwrap();
        assert!(outcome.is_inserted());

        let task = store.pop_next().await.unwrap().unwrap();
        assert_eq!(task.key, expected_key);
        assert_eq!(task.status, TaskStatus::Running);
        assert!(task.started_at.is_some());
    }

    #[tokio::test]
    async fn dedup_prevents_duplicate_key() {
        let store = test_store().await;
        let sub = make_submission("dup-key", Priority::NORMAL);

        let first = store.submit(&sub).await.unwrap();
        assert!(first.is_inserted());

        let second = store.submit(&sub).await.unwrap();
        assert_eq!(second, SubmitOutcome::Duplicate);
    }

    #[tokio::test]
    async fn dedup_upgrades_priority() {
        let store = test_store().await;

        let sub_normal = make_submission("upgrade-me", Priority::NORMAL);
        let first = store.submit(&sub_normal).await.unwrap();
        assert!(first.is_inserted());

        let sub_high = make_submission("upgrade-me", Priority::HIGH);
        let second = store.submit(&sub_high).await.unwrap();
        assert!(matches!(second, SubmitOutcome::Upgraded(_)));

        let key = sub_normal.effective_key();
        let task = store.task_by_key(&key).await.unwrap().unwrap();
        assert_eq!(task.priority, Priority::HIGH);

        let sub_bg = make_submission("upgrade-me", Priority::BACKGROUND);
        let third = store.submit(&sub_bg).await.unwrap();
        assert_eq!(third, SubmitOutcome::Duplicate);

        let task = store.task_by_key(&key).await.unwrap().unwrap();
        assert_eq!(task.priority, Priority::HIGH);
    }

    #[tokio::test]
    async fn dedup_requeues_when_running() {
        let store = test_store().await;

        let sub = make_submission("running-task", Priority::NORMAL);
        store.submit(&sub).await.unwrap();
        let task = store.pop_next().await.unwrap().unwrap();

        let sub_high = make_submission("running-task", Priority::HIGH);
        let outcome = store.submit(&sub_high).await.unwrap();
        assert!(matches!(outcome, SubmitOutcome::Requeued(_)));

        let key = sub.effective_key();
        let running = store.task_by_key(&key).await.unwrap().unwrap();
        assert!(running.requeue);
        assert_eq!(running.requeue_priority, Some(Priority::HIGH));

        store
            .complete(task.id, &TaskMetrics::default())
            .await
            .unwrap();

        let requeued = store.task_by_key(&key).await.unwrap().unwrap();
        assert_eq!(requeued.status, crate::task::TaskStatus::Pending);
        assert_eq!(requeued.priority, Priority::HIGH);
        assert!(!requeued.requeue);
        assert_eq!(requeued.requeue_priority, None);

        let popped = store.pop_next().await.unwrap().unwrap();
        assert_eq!(popped.id, task.id);
    }

    #[tokio::test]
    async fn dedup_requeue_already_requeued_same_priority() {
        let store = test_store().await;

        let sub = make_submission("rq-dup", Priority::NORMAL);
        store.submit(&sub).await.unwrap();
        store.pop_next().await.unwrap();

        let sub_high = make_submission("rq-dup", Priority::HIGH);
        let outcome = store.submit(&sub_high).await.unwrap();
        assert!(matches!(outcome, SubmitOutcome::Requeued(_)));

        let outcome2 = store.submit(&sub_high).await.unwrap();
        assert_eq!(outcome2, SubmitOutcome::Duplicate);
    }

    #[tokio::test]
    async fn dedup_requeue_upgrades_priority() {
        let store = test_store().await;

        let sub = make_submission("rq-upgrade", Priority::BACKGROUND);
        store.submit(&sub).await.unwrap();
        store.pop_next().await.unwrap();

        let sub_normal = make_submission("rq-upgrade", Priority::NORMAL);
        let outcome = store.submit(&sub_normal).await.unwrap();
        assert!(matches!(outcome, SubmitOutcome::Requeued(_)));

        let sub_high = make_submission("rq-upgrade", Priority::HIGH);
        let outcome2 = store.submit(&sub_high).await.unwrap();
        assert!(matches!(outcome2, SubmitOutcome::Requeued(_)));

        let key = sub.effective_key();
        let task = store.task_by_key(&key).await.unwrap().unwrap();
        assert_eq!(task.requeue_priority, Some(Priority::HIGH));
    }

    #[tokio::test]
    async fn permanent_failure_drops_requeue() {
        let store = test_store().await;

        let sub = make_submission("fail-rq", Priority::NORMAL);
        store.submit(&sub).await.unwrap();
        let task = store.pop_next().await.unwrap().unwrap();

        let sub_high = make_submission("fail-rq", Priority::HIGH);
        store.submit(&sub_high).await.unwrap();

        store
            .fail(task.id, "boom", false, 0, &TaskMetrics::default())
            .await
            .unwrap();

        let outcome = store.submit(&sub).await.unwrap();
        assert!(outcome.is_inserted());
    }

    #[tokio::test]
    async fn dedup_allows_same_key_different_types() {
        let store = test_store().await;

        let sub_a = TaskSubmission::new("type_a").key("shared-key");
        let sub_b = TaskSubmission::new("type_b").key("shared-key");

        let first = store.submit(&sub_a).await.unwrap();
        assert!(first.is_inserted());

        let second = store.submit(&sub_b).await.unwrap();
        assert!(second.is_inserted());
    }

    #[tokio::test]
    async fn dedup_by_payload_when_no_key() {
        let store = test_store().await;

        let sub = TaskSubmission::new("ingest").payload_raw(b"same-data".to_vec());

        let first = store.submit(&sub).await.unwrap();
        assert!(first.is_inserted());

        let second = store.submit(&sub).await.unwrap();
        assert_eq!(second, SubmitOutcome::Duplicate);

        let sub2 = TaskSubmission::new("ingest").payload_raw(b"different-data".to_vec());
        let third = store.submit(&sub2).await.unwrap();
        assert!(third.is_inserted());
    }

    #[tokio::test]
    async fn payload_size_limit() {
        use crate::store::StoreError;
        let store = test_store().await;
        let mut sub = make_submission("big", Priority::NORMAL);
        sub.payload = Some(vec![0u8; MAX_PAYLOAD_BYTES + 1]);

        let err = store.submit(&sub).await.unwrap_err();
        assert!(matches!(err, StoreError::PayloadTooLarge));
    }

    #[tokio::test]
    async fn submit_batch_inserts_all() {
        let store = test_store().await;
        let subs: Vec<_> = (0..5)
            .map(|i| make_submission(&format!("batch-{i}"), Priority::NORMAL))
            .collect();

        let results = store.submit_batch(&subs).await.unwrap();
        assert_eq!(results.len(), 5);
        assert!(results.iter().all(|r| r.is_inserted()));

        let count = store.pending_count().await.unwrap();
        assert_eq!(count, 5);
    }

    #[tokio::test]
    async fn submit_batch_dedup() {
        let store = test_store().await;
        let sub = make_submission("dup", Priority::NORMAL);

        let results = store
            .submit_batch(&[sub.clone(), sub.clone()])
            .await
            .unwrap();
        assert!(results[0].is_inserted());
        assert_eq!(results[1], SubmitOutcome::Duplicate);

        let results = store.submit_batch(&[sub]).await.unwrap();
        assert_eq!(results[0], SubmitOutcome::Duplicate);
    }

    #[tokio::test]
    async fn submit_batch_empty() {
        let store = test_store().await;
        let results = store.submit_batch(&[]).await.unwrap();
        assert!(results.is_empty());
    }

    #[tokio::test]
    async fn submit_batch_rejects_oversized_payload() {
        use crate::store::StoreError;
        let store = test_store().await;
        let sub = make_submission("ok", Priority::NORMAL);
        let big = TaskSubmission::new("test")
            .key("big")
            .payload_raw(vec![0u8; MAX_PAYLOAD_BYTES + 1]);

        let err = store.submit_batch(&[sub.clone(), big]).await.unwrap_err();
        assert!(matches!(err, StoreError::PayloadTooLarge));

        let count = store.pending_count().await.unwrap();
        assert_eq!(count, 0);
    }
}
