//! [`TaskSubmission`] — parameters for submitting a new task, and [`SubmitOutcome`].

use serde::{Deserialize, Serialize};

use crate::priority::Priority;

use super::dedup::generate_dedup_key;
use super::typed::TypedTask;

/// Result of a task submission attempt.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum SubmitOutcome {
    /// Task was inserted as new.
    Inserted(i64),
    /// Duplicate key existed; its priority was upgraded (pending/paused tasks only).
    Upgraded(i64),
    /// Duplicate key existed and is running/paused; marked for re-queue after completion.
    Requeued(i64),
    /// Duplicate key existed; no changes were made.
    Duplicate,
}

impl SubmitOutcome {
    /// Returns the task ID if the task was inserted, upgraded, or requeued.
    pub fn id(&self) -> Option<i64> {
        match self {
            Self::Inserted(id) | Self::Upgraded(id) | Self::Requeued(id) => Some(*id),
            Self::Duplicate => None,
        }
    }

    /// Returns `true` if a new task was inserted.
    pub fn is_inserted(&self) -> bool {
        matches!(self, Self::Inserted(_))
    }
}

/// Parameters for submitting a new task.
///
/// Use the builder-style constructor [`TaskSubmission::new`] for ergonomic
/// construction with sensible defaults:
///
/// ```ignore
/// use taskmill::{TaskSubmission, Priority};
///
/// let sub = TaskSubmission::new("thumbnail")
///     .key("img-001")
///     .priority(Priority::HIGH)
///     .payload_json(&my_payload)?
///     .expected_io(4096, 1024);
/// ```
///
/// For strongly-typed tasks, prefer [`TaskSubmission::from_typed`] or
/// [`Scheduler::submit_typed`](crate::Scheduler::submit_typed).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TaskSubmission {
    pub task_type: String,
    /// Optional dedup key. When `None`, the key is auto-generated by hashing
    /// `task_type` and `payload`, so two submissions with the same type and
    /// payload are deduplicated automatically.
    pub dedup_key: Option<String>,
    /// Human-readable label for UI display. Defaults to `dedup_key` (if set)
    /// or `task_type`. Override with [`label()`](Self::label) if needed.
    pub label: String,
    pub priority: Priority,
    pub payload: Option<Vec<u8>>,
    pub expected_read_bytes: i64,
    pub expected_write_bytes: i64,
    /// Estimated network receive bytes for IO budget scheduling.
    pub expected_net_rx_bytes: i64,
    /// Estimated network transmit bytes for IO budget scheduling.
    pub expected_net_tx_bytes: i64,
    /// Parent task ID for hierarchical tasks. Set automatically by
    /// [`TaskContext::spawn_child`](crate::TaskContext::spawn_child).
    pub parent_id: Option<i64>,
    /// When `true` (default), the first child failure cancels siblings and
    /// fails the parent immediately. When `false`, the parent waits for all
    /// children to finish before resolving. Only meaningful for parent tasks
    /// that spawn children.
    pub fail_fast: bool,
    /// Optional group key for per-group concurrency limiting.
    ///
    /// Tasks with the same group key share a concurrency budget controlled
    /// by [`SchedulerBuilder::group_concurrency`](crate::SchedulerBuilder::group_concurrency).
    /// Use this to prevent hammering a single endpoint (e.g. `"s3://my-bucket"`).
    pub group_key: Option<String>,
}

impl TaskSubmission {
    /// Create a new submission with sensible defaults.
    ///
    /// Defaults: `Priority::NORMAL`, no payload, no dedup key, zero IO
    /// estimates, no parent, fail-fast enabled.
    ///
    /// Chain builder methods to customise:
    ///
    /// ```ignore
    /// TaskSubmission::new("resize")
    ///     .key("my-file.jpg")
    ///     .priority(Priority::HIGH)
    ///     .payload_json(&data)?
    ///     .expected_io(4096, 1024)
    /// ```
    pub fn new(task_type: impl Into<String>) -> Self {
        let task_type = task_type.into();
        let label = task_type.clone();
        Self {
            task_type,
            dedup_key: None,
            label,
            priority: Priority::NORMAL,
            payload: None,
            expected_read_bytes: 0,
            expected_write_bytes: 0,
            expected_net_rx_bytes: 0,
            expected_net_tx_bytes: 0,
            parent_id: None,
            fail_fast: true,
            group_key: None,
        }
    }

    /// Set an explicit dedup key.
    ///
    /// When set, deduplication is based on `hash(task_type + ":" + key)`
    /// instead of the payload contents. Useful when different payloads
    /// represent the same logical work (e.g. same file path with different
    /// timestamps).
    pub fn key(mut self, key: impl Into<String>) -> Self {
        let key = key.into();
        self.label = key.clone();
        self.dedup_key = Some(key);
        self
    }

    /// Override the display label.
    ///
    /// By default the label is derived from the dedup key (if set via
    /// [`key()`](Self::key)) or the task type. Use this to provide a
    /// custom human-readable description for UI display.
    pub fn label(mut self, label: impl Into<String>) -> Self {
        self.label = label.into();
        self
    }

    /// Set the scheduling priority. Default: [`Priority::NORMAL`].
    pub fn priority(mut self, priority: Priority) -> Self {
        self.priority = priority;
        self
    }

    /// Set the payload from a serializable value (JSON-encoded).
    ///
    /// Returns an error if serialization fails. The payload can be
    /// deserialized in the executor via [`TaskContext::payload`](crate::TaskContext::payload).
    pub fn payload_json<T: serde::Serialize>(
        mut self,
        data: &T,
    ) -> Result<Self, serde_json::Error> {
        self.payload = Some(serde_json::to_vec(data)?);
        Ok(self)
    }

    /// Set the payload from raw bytes.
    pub fn payload_raw(mut self, data: Vec<u8>) -> Self {
        self.payload = Some(data);
        self
    }

    /// Set expected disk IO bytes for budget-based scheduling.
    ///
    /// The scheduler uses these estimates to avoid saturating disk throughput
    /// when [resource monitoring](crate::SchedulerBuilder::with_resource_monitoring)
    /// is enabled. Default: 0 for both.
    pub fn expected_io(mut self, read_bytes: i64, write_bytes: i64) -> Self {
        self.expected_read_bytes = read_bytes;
        self.expected_write_bytes = write_bytes;
        self
    }

    /// Set expected network IO bytes for budget-based scheduling.
    ///
    /// The scheduler uses these estimates to avoid saturating network bandwidth
    /// when [resource monitoring](crate::SchedulerBuilder::with_resource_monitoring)
    /// is enabled. Default: 0 for both.
    pub fn expected_net_io(mut self, rx_bytes: i64, tx_bytes: i64) -> Self {
        self.expected_net_rx_bytes = rx_bytes;
        self.expected_net_tx_bytes = tx_bytes;
        self
    }

    /// Set the group key for per-group concurrency limiting.
    ///
    /// Tasks with the same group key share a concurrency budget. Use this
    /// to prevent hammering a single endpoint (e.g. `"s3://my-bucket"`).
    pub fn group(mut self, group_key: impl Into<String>) -> Self {
        self.group_key = Some(group_key.into());
        self
    }

    /// Set the fail-fast flag for parent tasks that spawn children.
    ///
    /// When `true` (the default), the first child failure cancels siblings
    /// and fails the parent immediately. When `false`, the parent waits for
    /// all children to finish before resolving.
    pub fn fail_fast(mut self, fail_fast: bool) -> Self {
        self.fail_fast = fail_fast;
        self
    }

    /// Resolve the effective dedup key. Always incorporates the task type
    /// so different task types never collide, even with the same logical key.
    ///
    /// - Explicit key: `hash(task_type + ":" + key)`
    /// - No key: `hash(task_type + ":" + payload)`
    pub fn effective_key(&self) -> String {
        match &self.dedup_key {
            Some(k) => generate_dedup_key(&self.task_type, Some(k.as_bytes())),
            None => generate_dedup_key(&self.task_type, self.payload.as_deref()),
        }
    }

    /// Create a submission with a typed payload serialized to JSON bytes.
    ///
    /// The dedup key is auto-generated from the task type and serialized payload.
    /// Use `TaskRecord::deserialize_payload()` on the executor side to recover the type.
    #[deprecated(
        since = "2.0.0",
        note = "use `TaskSubmission::new(task_type).payload_json(&data)?.priority(p).expected_io(r, w)` instead"
    )]
    pub fn with_payload<T: serde::Serialize>(
        task_type: &str,
        priority: Priority,
        data: &T,
        expected_read_bytes: i64,
        expected_write_bytes: i64,
    ) -> Result<Self, serde_json::Error> {
        Ok(Self::new(task_type)
            .priority(priority)
            .payload_json(data)?
            .expected_io(expected_read_bytes, expected_write_bytes))
    }

    /// Create a submission from a [`TypedTask`], serializing the payload and
    /// pulling task type, priority, IO estimates, and group key from the trait.
    pub fn from_typed<T: TypedTask>(task: &T) -> Result<Self, serde_json::Error> {
        let mut sub = Self::new(T::TASK_TYPE)
            .priority(task.priority())
            .payload_json(task)?
            .expected_io(task.expected_read_bytes(), task.expected_write_bytes())
            .expected_net_io(task.expected_net_rx_bytes(), task.expected_net_tx_bytes());
        sub.group_key = task.group_key();
        Ok(sub)
    }
}
