//! [`TaskSubmission`] — parameters for submitting a new task, and [`SubmitOutcome`].

use serde::{Deserialize, Serialize};

use crate::priority::Priority;

use super::dedup::generate_dedup_key;
use super::typed::TypedTask;
use super::IoBudget;

/// Result of a task submission attempt.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum SubmitOutcome {
    /// Task was inserted as new.
    Inserted(i64),
    /// Duplicate key existed; its priority was upgraded (pending/paused tasks only).
    Upgraded(i64),
    /// Duplicate key existed and is running/paused; marked for re-queue after completion.
    Requeued(i64),
    /// Duplicate key existed; no changes were made.
    Duplicate,
}

impl SubmitOutcome {
    /// Returns the task ID if the task was inserted, upgraded, or requeued.
    pub fn id(&self) -> Option<i64> {
        match self {
            Self::Inserted(id) | Self::Upgraded(id) | Self::Requeued(id) => Some(*id),
            Self::Duplicate => None,
        }
    }

    /// Returns `true` if a new task was inserted.
    pub fn is_inserted(&self) -> bool {
        matches!(self, Self::Inserted(_))
    }
}

/// Parameters for submitting a new task.
///
/// Use the builder-style constructor [`TaskSubmission::new`] for ergonomic
/// construction with sensible defaults:
///
/// ```ignore
/// use taskmill::{TaskSubmission, Priority, IoBudget};
///
/// let sub = TaskSubmission::new("thumbnail")
///     .key("img-001")
///     .priority(Priority::HIGH)
///     .payload_json(&my_payload)?
///     .expected_io(IoBudget::disk(4096, 1024));
/// ```
///
/// For strongly-typed tasks, prefer [`TaskSubmission::from_typed`] or
/// [`Scheduler::submit_typed`](crate::Scheduler::submit_typed).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TaskSubmission {
    pub task_type: String,
    /// Optional dedup key. When `None`, the key is auto-generated by hashing
    /// `task_type` and `payload`, so two submissions with the same type and
    /// payload are deduplicated automatically.
    pub dedup_key: Option<String>,
    /// Human-readable label for UI display. Defaults to `dedup_key` (if set)
    /// or `task_type`. Override with [`label()`](Self::label) if needed.
    pub label: String,
    pub priority: Priority,
    pub payload: Option<Vec<u8>>,
    /// Expected IO budget for scheduling.
    pub expected_io: IoBudget,
    /// Parent task ID for hierarchical tasks. Set automatically by
    /// [`TaskContext::spawn_child`](crate::TaskContext::spawn_child).
    pub parent_id: Option<i64>,
    /// When `true` (default), the first child failure cancels siblings and
    /// fails the parent immediately. When `false`, the parent waits for all
    /// children to finish before resolving. Only meaningful for parent tasks
    /// that spawn children.
    pub fail_fast: bool,
    /// Optional group key for per-group concurrency limiting.
    ///
    /// Tasks with the same group key share a concurrency budget controlled
    /// by [`SchedulerBuilder::group_concurrency`](crate::SchedulerBuilder::group_concurrency).
    /// Use this to prevent hammering a single endpoint (e.g. `"s3://my-bucket"`).
    pub group_key: Option<String>,
    /// Deferred serialization error from [`payload_json`](Self::payload_json).
    /// Surfaced at submit time as [`StoreError::Serialization`](crate::StoreError::Serialization).
    #[serde(skip)]
    pub(crate) payload_error: Option<String>,
}

impl TaskSubmission {
    /// Create a new submission with sensible defaults.
    ///
    /// Defaults: `Priority::NORMAL`, no payload, no dedup key, zero IO
    /// estimates, no parent, fail-fast enabled.
    ///
    /// Chain builder methods to customise:
    ///
    /// ```ignore
    /// TaskSubmission::new("resize")
    ///     .key("my-file.jpg")
    ///     .priority(Priority::HIGH)
    ///     .payload_json(&data)
    ///     .expected_io(IoBudget::disk(4096, 1024))
    /// ```
    pub fn new(task_type: impl Into<String>) -> Self {
        let task_type = task_type.into();
        let label = task_type.clone();
        Self {
            task_type,
            dedup_key: None,
            label,
            priority: Priority::NORMAL,
            payload: None,
            expected_io: IoBudget::default(),
            parent_id: None,
            fail_fast: true,
            group_key: None,
            payload_error: None,
        }
    }

    /// Set an explicit dedup key.
    ///
    /// When set, deduplication is based on `hash(task_type + ":" + key)`
    /// instead of the payload contents. Useful when different payloads
    /// represent the same logical work (e.g. same file path with different
    /// timestamps).
    pub fn key(mut self, key: impl Into<String>) -> Self {
        let key = key.into();
        self.label = key.clone();
        self.dedup_key = Some(key);
        self
    }

    /// Override the display label.
    ///
    /// By default the label is derived from the dedup key (if set via
    /// [`key()`](Self::key)) or the task type. Use this to provide a
    /// custom human-readable description for UI display.
    pub fn label(mut self, label: impl Into<String>) -> Self {
        self.label = label.into();
        self
    }

    /// Set the scheduling priority. Default: [`Priority::NORMAL`].
    pub fn priority(mut self, priority: Priority) -> Self {
        self.priority = priority;
        self
    }

    /// Set the payload from a serializable value (JSON-encoded).
    ///
    /// Serialization errors are deferred to submit time so the builder
    /// chain is never interrupted. The payload can be deserialized in
    /// the executor via [`TaskContext::payload`](crate::TaskContext::payload).
    pub fn payload_json<T: serde::Serialize>(mut self, data: &T) -> Self {
        match serde_json::to_vec(data) {
            Ok(bytes) => self.payload = Some(bytes),
            Err(e) => self.payload_error = Some(e.to_string()),
        }
        self
    }

    /// Set the payload from raw bytes.
    pub fn payload_raw(mut self, data: Vec<u8>) -> Self {
        self.payload = Some(data);
        self
    }

    /// Set the expected IO budget for scheduling.
    pub fn expected_io(mut self, budget: IoBudget) -> Self {
        self.expected_io = budget;
        self
    }

    /// Set the group key for per-group concurrency limiting.
    ///
    /// Tasks with the same group key share a concurrency budget. Use this
    /// to prevent hammering a single endpoint (e.g. `"s3://my-bucket"`).
    pub fn group(mut self, group_key: impl Into<String>) -> Self {
        self.group_key = Some(group_key.into());
        self
    }

    /// Set the fail-fast flag for parent tasks that spawn children.
    ///
    /// When `true` (the default), the first child failure cancels siblings
    /// and fails the parent immediately. When `false`, the parent waits for
    /// all children to finish before resolving.
    pub fn fail_fast(mut self, fail_fast: bool) -> Self {
        self.fail_fast = fail_fast;
        self
    }

    /// Resolve the effective dedup key. Always incorporates the task type
    /// so different task types never collide, even with the same logical key.
    ///
    /// - Explicit key: `hash(task_type + ":" + key)`
    /// - No key: `hash(task_type + ":" + payload)`
    pub fn effective_key(&self) -> String {
        match &self.dedup_key {
            Some(k) => generate_dedup_key(&self.task_type, Some(k.as_bytes())),
            None => generate_dedup_key(&self.task_type, self.payload.as_deref()),
        }
    }

    /// Create a submission from a [`TypedTask`], serializing the payload and
    /// pulling task type, priority, IO estimates, key, label, and group key
    /// from the trait.
    pub fn from_typed<T: TypedTask>(task: &T) -> Self {
        let mut sub = Self::new(T::TASK_TYPE)
            .priority(task.priority())
            .payload_json(task)
            .expected_io(task.expected_io());
        if let Some(k) = task.key() {
            sub = sub.key(k);
        }
        if let Some(l) = task.label() {
            sub = sub.label(l);
        }
        if let Some(g) = task.group_key() {
            sub = sub.group(g);
        }
        sub
    }
}
